/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.espe.vista;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Paul
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
private JPanel contenedorPrincipal;
    private CardLayout cardLayout;

    private PanelDocente panelDocente;    
    private PanelEstudiante panelEstudiante;  
    private PanelAsignaturas panelAsignaturas;   
    private PanelMatricula panelMatricula;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        configurarVentana();
        inicializarComponentes();
        configurarMenu();
        initComponents();
    }
    
    
    private void configurarVentana() {
        setTitle("Sistema de Gestión Académica - MongoDB");
        setSize(900, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private void inicializarComponentes() {
        cardLayout = new CardLayout();
        contenedorPrincipal = new JPanel(cardLayout);

        panelDocente = new PanelDocente();
        panelEstudiante = new PanelEstudiante();
        panelAsignaturas = new PanelAsignaturas();
        panelMatricula = new PanelMatricula();


        contenedorPrincipal.add(panelDocente, "DOCENTES");
        contenedorPrincipal.add(panelEstudiante, "ESTUDIANTES");
        contenedorPrincipal.add(panelAsignaturas, "ASIGNATURAS");
        contenedorPrincipal.add(panelMatricula, "MATRICULA");

        add(contenedorPrincipal, BorderLayout.CENTER);
    }

    private void configurarMenu() {
        JMenuBar menuBar = new JMenuBar();

        JMenu menuGestion = new JMenu("Gestión Académica");

        JMenuItem itemUsuarios = new JMenuItem("Usuarios ");
        JMenuItem itemAsignaturas = new JMenuItem("Asignaturas ");
        JMenuItem itemMatricula = new JMenuItem("Matriculación ");

        itemUsuarios.addActionListener(e -> cardLayout.show(contenedorPrincipal, "USUARIOS"));
        itemAsignaturas.addActionListener(e -> cardLayout.show(contenedorPrincipal, "ASIGNATURAS"));
        itemMatricula.addActionListener(e -> cardLayout.show(contenedorPrincipal, "MATRICULA"));

        menuGestion.add(itemUsuarios);
        menuGestion.add(itemAsignaturas);
        menuGestion.addSeparator();
        menuGestion.add(itemMatricula);
        
        menuBar.add(menuGestion);
        setJMenuBar(menuBar);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
